//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Management_System.Resources.Client.RegisterResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Book_Management_System.Resources.Client.RegisterResource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu.
        /// </summary>
        public static string Confirm_password {
            get {
                return ResourceManager.GetString("Confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ không thể để trống.
        /// </summary>
        public static string Empty_Address {
            get {
                return ResourceManager.GetString("Empty_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu không thể để trống.
        /// </summary>
        public static string Empty_Confirm_Password {
            get {
                return ResourceManager.GetString("Empty_Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không thể để trống.
        /// </summary>
        public static string Empty_Email {
            get {
                return ResourceManager.GetString("Empty_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không thể để trống.
        /// </summary>
        public static string Empty_Firstname {
            get {
                return ResourceManager.GetString("Empty_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn giới tính của bạn.
        /// </summary>
        public static string Empty_Gender {
            get {
                return ResourceManager.GetString("Empty_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ không thể để trống.
        /// </summary>
        public static string Empty_Lastname {
            get {
                return ResourceManager.GetString("Empty_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được để trống.
        /// </summary>
        public static string Empty_Password {
            get {
                return ResourceManager.GetString("Empty_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngươi dùng không được để trống.
        /// </summary>
        public static string Empty_Username {
            get {
                return ResourceManager.GetString("Empty_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày không hợp lệ.
        /// </summary>
        public static string Format_Birthday {
            get {
                return ResourceManager.GetString("Format_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ.
        /// </summary>
        public static string Format_Email {
            get {
                return ResourceManager.GetString("Format_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải có 6-30 ký tự, ít nhất một chữ cái viết hoa, một chữ cái viết thường, một số và không có khoảng trắng (cho phép kí tự đặc biệt).
        /// </summary>
        public static string Format_Password {
            get {
                return ResourceManager.GetString("Format_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không trùng nhau.
        /// </summary>
        public static string Identical_Password {
            get {
                return ResourceManager.GetString("Identical_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email này không có sẵn, vui lòng chọn một email khác.
        /// </summary>
        public static string Invalid_Email {
            get {
                return ResourceManager.GetString("Invalid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng này không có sẵn, vui lòng chọn một tên khác.
        /// </summary>
        public static string Invalid_Username {
            get {
                return ResourceManager.GetString("Invalid_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu phải có ít nhất 6 ký tự.
        /// </summary>
        public static string Length_Confirm_Password {
            get {
                return ResourceManager.GetString("Length_Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không thể nhiều hơn 100 ký tự.
        /// </summary>
        public static string Length_Email {
            get {
                return ResourceManager.GetString("Length_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phải có ít nhất 2 và ít hơn 50 ký tự.
        /// </summary>
        public static string Length_Firstname {
            get {
                return ResourceManager.GetString("Length_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ phải có ít nhất 2 và ít hơn 50 ký tự.
        /// </summary>
        public static string Length_Lastname {
            get {
                return ResourceManager.GetString("Length_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải có ít nhất 6 và ít hơn 30 ký tự.
        /// </summary>
        public static string Length_Password {
            get {
                return ResourceManager.GetString("Length_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng phải có nhiều hơn 6 ký tự.
        /// </summary>
        public static string Length_Username {
            get {
                return ResourceManager.GetString("Length_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập địa chỉ.
        /// </summary>
        public static string PH_Address {
            get {
                return ResourceManager.GetString("PH_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/DD/YYYY.
        /// </summary>
        public static string PH_Birthday {
            get {
                return ResourceManager.GetString("PH_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        public static string PH_Confirm_password {
            get {
                return ResourceManager.GetString("PH_Confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập email.
        /// </summary>
        public static string PH_Email {
            get {
                return ResourceManager.GetString("PH_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập họ.
        /// </summary>
        public static string PH_Firstname {
            get {
                return ResourceManager.GetString("PH_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên.
        /// </summary>
        public static string PH_Lastname {
            get {
                return ResourceManager.GetString("PH_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mật khẩu.
        /// </summary>
        public static string PH_Password {
            get {
                return ResourceManager.GetString("PH_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên tài khoản.
        /// </summary>
        public static string PH_Username {
            get {
                return ResourceManager.GetString("PH_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
