//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Management_System.Resources.Client.CartResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Book_Management_System.Resources.Client.CartResource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sách hết hàng dòi. Chọn quyển khác nhaa .
        /// </summary>
        public static string Book_IsDeleted {
            get {
                return ResourceManager.GetString("Book_IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vào đăng nhập rồi mới chọn sách nha người ơi  .
        /// </summary>
        public static string Cart_Add_Fail_Log_In {
            get {
                return ResourceManager.GetString("Cart_Add_Fail_Log_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm vào giỏ hàng thành công.
        /// </summary>
        public static string Cart_Add_Success {
            get {
                return ResourceManager.GetString("Cart_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string Cart_All {
            get {
                return ResourceManager.GetString("Cart_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tất cả sách.
        /// </summary>
        public static string Cart_ChooseAllBook {
            get {
                return ResourceManager.GetString("Cart_ChooseAllBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vào lại cửa hàng và chọn quyển sách bạn thích nhé.
        /// </summary>
        public static string Cart_ChooseSth {
            get {
                return ResourceManager.GetString("Cart_ChooseSth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn quyển sách này.
        /// </summary>
        public static string Cart_ChooseThisBook {
            get {
                return ResourceManager.GetString("Cart_ChooseThisBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa.
        /// </summary>
        public static string Cart_Deleted {
            get {
                return ResourceManager.GetString("Cart_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sách của bạn đã được xóa.
        /// </summary>
        public static string Cart_Deleted_Info {
            get {
                return ResourceManager.GetString("Cart_Deleted_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bỏ chọn tất cả sách.
        /// </summary>
        public static string Cart_DontChooseAllBook {
            get {
                return ResourceManager.GetString("Cart_DontChooseAllBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bỏ chọn quyển sách này .
        /// </summary>
        public static string Cart_DontChooseThisBook {
            get {
                return ResourceManager.GetString("Cart_DontChooseThisBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không còn món hàng nào trong giỏ hàng của bạn .
        /// </summary>
        public static string Cart_Empty {
            get {
                return ResourceManager.GetString("Cart_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem giỏ hàng.
        /// </summary>
        public static string Cart_GoTo {
            get {
                return ResourceManager.GetString("Cart_GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string Cart_Image {
            get {
                return ResourceManager.GetString("Cart_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoi anh không chơi.
        /// </summary>
        public static string Cart_No {
            get {
                return ResourceManager.GetString("Cart_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        public static string Cart_Payment {
            get {
                return ResourceManager.GetString("Cart_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        public static string Cart_Price {
            get {
                return ResourceManager.GetString("Cart_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string Cart_Quantity {
            get {
                return ResourceManager.GetString("Cart_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn chứ ?.
        /// </summary>
        public static string Cart_SureQuestion {
            get {
                return ResourceManager.GetString("Cart_SureQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string Cart_Title {
            get {
                return ResourceManager.GetString("Cart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng cộng.
        /// </summary>
        public static string Cart_Total {
            get {
                return ResourceManager.GetString("Cart_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật giỏ hàng thất bại.
        /// </summary>
        public static string Cart_Update_Fail {
            get {
                return ResourceManager.GetString("Cart_Update_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật giỏ hàng thành công.
        /// </summary>
        public static string Cart_Update_Success {
            get {
                return ResourceManager.GetString("Cart_Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bút sa là gà chết nhá.
        /// </summary>
        public static string Cart_Warning {
            get {
                return ResourceManager.GetString("Cart_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quất ! Tao lại sợ mày quá cơ .
        /// </summary>
        public static string Cart_Yes {
            get {
                return ResourceManager.GetString("Cart_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Log_In {
            get {
                return ResourceManager.GetString("Log_In", resourceCulture);
            }
        }
    }
}
