//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Management_System.Resources.Client.HomeResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Book_Management_System.Resources.Client.HomeResource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chim khôn kêu tiếng rãnh rang người khôn bình luận dịu dàng dễ nghe.
        /// </summary>
        public static string Cmt_Content {
            get {
                return ResourceManager.GetString("Cmt_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bạn là gì ?.
        /// </summary>
        public static string Cmt_InputName {
            get {
                return ResourceManager.GetString("Cmt_InputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chia sẻ.
        /// </summary>
        public static string Cmt_Share {
            get {
                return ResourceManager.GetString("Cmt_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm vào giỏ hàng.
        /// </summary>
        public static string Home_AddToCart {
            get {
                return ResourceManager.GetString("Home_AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tác giả.
        /// </summary>
        public static string Home_Author {
            get {
                return ResourceManager.GetString("Home_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua hàng.
        /// </summary>
        public static string Home_BuyNow {
            get {
                return ResourceManager.GetString("Home_BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng.
        /// </summary>
        public static string Home_Cart {
            get {
                return ResourceManager.GetString("Home_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string Home_Cate {
            get {
                return ResourceManager.GetString("Home_Cate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm nổi bật.
        /// </summary>
        public static string Home_Feature {
            get {
                return ResourceManager.GetString("Home_Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Home_Login {
            get {
                return ResourceManager.GetString("Home_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string Home_Logout {
            get {
                return ResourceManager.GetString("Home_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế tiếp.
        /// </summary>
        public static string Home_Next {
            get {
                return ResourceManager.GetString("Home_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        public static string Home_Payment {
            get {
                return ResourceManager.GetString("Home_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        public static string Home_Prev {
            get {
                return ResourceManager.GetString("Home_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng kí.
        /// </summary>
        public static string Home_Register {
            get {
                return ResourceManager.GetString("Home_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng cộng.
        /// </summary>
        public static string Home_Total {
            get {
                return ResourceManager.GetString("Home_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào.
        /// </summary>
        public static string Home_Welcome {
            get {
                return ResourceManager.GetString("Home_Welcome", resourceCulture);
            }
        }
    }
}
