//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Management_System.Resources.Admin.Book {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Book_Management_System.Resources.Admin.Book.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới sách.
        /// </summary>
        public static string AddBook {
            get {
                return ResourceManager.GetString("AddBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tác giả.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lí sách.
        /// </summary>
        public static string BookManagement {
            get {
                return ResourceManager.GetString("BookManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string Createdate {
            get {
                return ResourceManager.GetString("Createdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo không được trống.
        /// </summary>
        public static string CreatedateErrorEmpty {
            get {
                return ResourceManager.GetString("CreatedateErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai định dạng .
        /// </summary>
        public static string CreatedateErrorRegexp {
            get {
                return ResourceManager.GetString("CreatedateErrorRegexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấn vào để chọn ngày.
        /// </summary>
        public static string CreatedatePlace {
            get {
                return ResourceManager.GetString("CreatedatePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi thông tin sách.
        /// </summary>
        public static string EditBook {
            get {
                return ResourceManager.GetString("EditBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tóm tắt bằng tiếng anh.
        /// </summary>
        public static string EnSummary {
            get {
                return ResourceManager.GetString("EnSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tóm tắt không được trống.
        /// </summary>
        public static string EnSummaryErrorEmpty {
            get {
                return ResourceManager.GetString("EnSummaryErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tóm tắt phải ít nhất 6 ký tự.
        /// </summary>
        public static string EnSummaryErrorLength {
            get {
                return ResourceManager.GetString("EnSummaryErrorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tóm tắt nội dụng sách bằng tiếng anh.
        /// </summary>
        public static string EnSummaryPlace {
            get {
                return ResourceManager.GetString("EnSummaryPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sách bằng tiếng anh.
        /// </summary>
        public static string EnTitle {
            get {
                return ResourceManager.GetString("EnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sách không được trống.
        /// </summary>
        public static string EnTitleErrorEmpty {
            get {
                return ResourceManager.GetString("EnTitleErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sách phải ít nhất 6 kí tự.
        /// </summary>
        public static string EnTitleErrorLength {
            get {
                return ResourceManager.GetString("EnTitleErrorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên sách bằng tiếng anh.
        /// </summary>
        public static string EnTitlePlace {
            get {
                return ResourceManager.GetString("EnTitlePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh không được trống.
        /// </summary>
        public static string ImageErrorEmpty {
            get {
                return ResourceManager.GetString("ImageErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh phải có phần mở rộng [ jpeg, png, gif, jpg ].
        /// </summary>
        public static string ImageErrorRegexp {
            get {
                return ResourceManager.GetString("ImageErrorRegexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh.
        /// </summary>
        public static string ImageURL {
            get {
                return ResourceManager.GetString("ImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string ISBN {
            get {
                return ResourceManager.GetString("ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN không được trống.
        /// </summary>
        public static string ISBNErrorEmpty {
            get {
                return ResourceManager.GetString("ISBNErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN phải từ 6 đến 30 ký tự.
        /// </summary>
        public static string ISBNErrorLength {
            get {
                return ResourceManager.GetString("ISBNErrorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN không được phép chứa chữ và ký tự đặc biệt.
        /// </summary>
        public static string ISBNErrorRegexp {
            get {
                return ResourceManager.GetString("ISBNErrorRegexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã ISBN của sách.
        /// </summary>
        public static string ISBNPlace {
            get {
                return ResourceManager.GetString("ISBNPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày chỉnh sửa.
        /// </summary>
        public static string Modifieddate {
            get {
                return ResourceManager.GetString("Modifieddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá không được trống.
        /// </summary>
        public static string PriceErrorEmpty {
            get {
                return ResourceManager.GetString("PriceErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá không chứa kí tự và lớn hơn 0.
        /// </summary>
        public static string PriceErrorRegexp {
            get {
                return ResourceManager.GetString("PriceErrorRegexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập giá sách.
        /// </summary>
        public static string PricePlace {
            get {
                return ResourceManager.GetString("PricePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà phát hành.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng không được trống.
        /// </summary>
        public static string QuantityErrorEmpty {
            get {
                return ResourceManager.GetString("QuantityErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng không chứa kí tự và lớn hơn 0.
        /// </summary>
        public static string QuantityErrorRegexp {
            get {
                return ResourceManager.GetString("QuantityErrorRegexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số lượng sách.
        /// </summary>
        public static string QuantityPlace {
            get {
                return ResourceManager.GetString("QuantityPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tóm tắt.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tóm tắt không được trống.
        /// </summary>
        public static string SummaryErrorEmpty {
            get {
                return ResourceManager.GetString("SummaryErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tóm tắt phải ít nhất 6 ký tự.
        /// </summary>
        public static string SummaryErrorLength {
            get {
                return ResourceManager.GetString("SummaryErrorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tóm tắt nội dụng sách.
        /// </summary>
        public static string SummaryPlace {
            get {
                return ResourceManager.GetString("SummaryPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sách.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sách không được trống.
        /// </summary>
        public static string TitleErrorEmpty {
            get {
                return ResourceManager.GetString("TitleErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sách phải ít nhất 6 kí tự.
        /// </summary>
        public static string TitleErrorLength {
            get {
                return ResourceManager.GetString("TitleErrorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên sách.
        /// </summary>
        public static string TitlePlace {
            get {
                return ResourceManager.GetString("TitlePlace", resourceCulture);
            }
        }
    }
}
